version: '3'
services:
  mongodb:
    container_name: quickpoll-mongodb
    image: mongo:7.0
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - ./mongodb-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: test-admin
      MONGO_INITDB_ROOT_PASSWORD: test-password
      MONGO_INITDB_DATABASE: testing

  client:
    container_name: quickpoll-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - server

  server:
    container_name: quickpoll-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
