version: '3'
services:
  mongodb:
    container_name: quickpoll-mongodb
    image: mongo:7.0
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - ./mongodb-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    env_file:
      - .env

  client:
    container_name: quickpoll-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
    volumes:
      - ./client:/app
      - '/app/node_modules'

  server:
    container_name: quickpoll-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - app-network
    environment:
      MONGO_URL: ${MONGO_URL}
      PORT: 8000
    volumes:
      - ./server:/app
      - '/app/node_modules'
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
